name: Build and release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull sophgo/tpuc_dev:latest

    - name: Run Docker container
      run: |
        echo "GIT_SHORT_HASH"

        docker run --privileged --name myname1234 -v $PWD:/workspace sophgo/tpuc_dev:v2.2 /bin/bash -c "
          ./release.sh
        "

    - name: Find and copy .tar.gz file
      run: |
        docker start myname1234
        FILE_PATH=$(docker exec myname1234 find /workspace -type f -name "*.tar.gz" -print -quit)
        if [ -n "$FILE_PATH" ]; then
          docker cp myname1234:"$FILE_PATH" ./
          ls -al
          pwd
        else
          echo "File not found in container"
        fi
        FILE_PATH=${FILE_PATH#/workspace/}
        echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: >-
        gh release create ${{ env.FILE_PATH }}
        "./${{ env.FILE_PATH }}"
        --generate-notes
        --title "Release ${{ env.FILE_PATH }}"

