name: Build and release

on:
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Git Tag
      id: get_git_tag
      run: |
        GIT_TAG=$(git describe --tags --always)
        echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV

    - name: Pull Docker image
      run: docker pull sophgo/tpuc_dev:latest

    - name: Run Docker container
      run: |
        git describe --tags --always

        docker run --privileged --name myname1234 -v $PWD:/workspace sophgo/tpuc_dev:v2.2 /bin/bash -c "
          ./release.sh
        "

    - name: Find and copy .tar.gz file
      run: |
        docker start myname1234
        FILE_PATH=$(docker exec myname1234 find /workspace -type f -name "*.tar.gz" -print -quit)
        if [ -n "$FILE_PATH" ]; then
          docker cp myname1234:"$FILE_PATH" ./
          ls -al
          pwd
        else
          echo "File not found in container"
        fi
        FILE_PATH=${FILE_PATH#/workspace/}
        echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: >-
        gh release create ${{ env.GIT_TAG }}
        "./${{ env.FILE_PATH }}"
        --generate-notes
        --title "Release ${{ env.FILE_PATH }}"

