name: Tpu-mlir Regression Testing

on: [push]

jobs:
  


  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
 
    
      - name: 设置 Node.js
        uses: actions/setup-node@master
    
      - run: npm init -y
      - run: npm run build --if-present
      
      - name: Pull Docker images
        run: |
            docker pull sophgo/tpuc_dev:latest
      - name: Run Docker Container and YOLOv5 Test
        run: |
          docker run --privileged --name github_test -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '
          cd tpu-mlir
          source ./envsetup.sh
          ./build.sh
        
           cd regression 
           ./run.sh 
           '
