name: Upload Release Assets




on:
  push:
 

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get system time
        id: system-time
        run: echo "::set-output name=ss::$(date +'%Y-%m-%d %H:%M:%S')"
    

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v11.0.0
          release_name: Release v11.0.0
          body: This is the release description.
          draft: false
          prerelease: false
      - name: Find TAR.GZ Files
        id: find_tar_gz
        run: |
          tar_gz_files=$(find . -type f -name "*.tar.gz")
          echo "::set-output name=tar_gz_files::$tar_gz_files"
        continue-on-error: true


  

        
      - name: Upload Release Assets
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:  ${{ steps.find_tar_gz.outputs.tar_gz_files }}
          asset_name: tar_gz_files.zip  # 上传后的文件名
          asset_content_type: application/zip  # 文件类型

    

