name: Upload Release Assets

on:
  push:
    # 配置适当的分支触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull sophgo/tpuc_dev:latest

      - name: Run Docker container
        run: |
          docker run --privileged --name myname1234 -v $PWD:/workspace sophgo/tpuc_dev:v2.2 /bin/bash -c "
          ./release.sh

         
          "

      - name: Find and copy .tar.gz file
        run: |
          docker start myname1234
          FILE_PATH=$(docker exec myname1234 find /workspace -type f -name "*.tar.gz" -print -quit)
          if [ -n "$FILE_PATH" ]; then
            docker cp myname1234:"$FILE_PATH" $GITHUB_WORKSPACE/
            
          else
            echo "File not found in container"
          fi
      - name: Create Release # 创建Release，可以在仓库看到一个个版本
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # 之前GitHub添加的Token
        with:
          tag_name:  tpu-mlir_v1.3.beta.0-20230813.tar.gz
          release_name: tpu-mlir_v1.3.beta.0-20230813.tar.gz
          draft: false # 是否是草稿
          prerelease: false # 是否是预发布
    
