name: Regression Testing

on:
  push:

jobs:
  reuse_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


 # 第二步：打包构建
      - name: Build release
        uses: actions/setup-node@v1
      - run: | 
             npm init -y
             npm run build --if-present # 打包
    
      # 把.nuxt、nuxt.config.js等文件，打包压缩为release.tgz




      - name: Pull Docker images
        run: |
          docker pull sophgo/tpuc_dev:latest


      - name: Run Docker Container and YOLOv5 Test
        run: |
          docker run --privileged --name github_actions_test -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '

      
          cd tpu-mlir
          source ./envsetup.sh
          ./build.sh

          mkdir model_yolov5s && cd model_yolov5s
          cp ${REGRESSION_PATH}/model/yolov5s.onnx .
          cp -rf ${REGRESSION_PATH}/dataset/COCO2017 .
          cp -rf ${REGRESSION_PATH}/image .
          mkdir workspace && cd workspace
          
          ########### Model to MLIR ###############
          
          model_transform.py \
             --model_name yolov5s \
             --model_def ../yolov5s.onnx \
             --input_shapes [[1,3,640,640]] \
             --mean 0.0,0.0,0.0 \
             --scale 0.0039216,0.0039216,0.0039216 \
             --keep_aspect_ratio \
             --pixel_format rgb \
             --output_names 350,498,646 \
             --test_input ../image/dog.jpg \
             --test_result yolov5s_top_outputs.npz \
             --mlir yolov5s.mlir

          '


          


          




