name: Update Pip and Build


jobs:
  build:
    runs-on: ubuntu-latest

on:
  push:
    branches:
      - master # 修改为您的默认分支

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.10

    # - name: Upgrade pip
    #   run: |
    #     python -m pip install --upgrade pip

    # - name: Build and Publish
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.PYPITOKEN }}
    #   run: |
       
    #     python setup.py sdist 
        
    #     pip install twine

     
         
    #     twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

    #     twine upload dist/*  --verbose




    - name: Run Docker Container and YOLOv5 Test
      run: |
          docker run --privileged --name github_actions_test -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '


          cd tpu-mlir
          source ./envsetup.sh
          ./build.sh
          python setup.py build


      steps:
      - uses: actions/checkout@v3


      - name: Run Docker Container and YOLOv5 Test
        run: |
          docker run --privileged --name github_actions_test -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '


          cd tpu-mlir
          source ./envsetup.sh
          ./build.sh
          python setup.py build
          python setup.py bdist_wheel

       
         
    
             '





