name: Cache Docker Container Build

on:
  push:
  
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
     

   

      - name: Pull Docker images
        run: |
          docker pull sophgo/tpuc_dev:latest
      - name: Run Docker Container and YOLOv5 Test
        run: |
          docker run --privileged --name github_actions_test -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '

      
          cd tpu-mlir
          source ./envsetup.sh
          ./build.sh
           '
         
      - name: Save cache
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
