name: Tpu-mlir Regression Testing

on:
  push:
    
        

jobs:
  reuse_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

 # 第二步：打包构建
      - name: Build
        uses: actions/setup-node@master
      - run: npm init -y
      - run: npm run build --if-present # 打包
      - run: tar -zcvf release.tgz  package.json 
      # 把.nuxt、nuxt.config.js等文件，打包压缩为release.tgz


 


      - name: Pull Docker images
        run: |
          docker pull sophgo/tpuc_dev:latest


      - name: Run Docker Container and YOLOv5 Test
        run: |
          docker run --privileged --name github_actions_test -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '

      
          source ./envsetup.sh
          ./build.sh

          mkdir model_yolov5s && cd model_yolov5s
          cp ${REGRESSION_PATH}/model/yolov5s.onnx .
          cp -rf ${REGRESSION_PATH}/dataset/COCO2017 .
          cp -rf ${REGRESSION_PATH}/image .
          mkdir workspace && cd workspace
          
          ########### Model to MLIR ###############
          
        
             
           ############   yolov5 regression test   ###########
             - name:  yolov5 regression test
           cd ..
           cd ..
           cd regression 
           ./run.sh
           
           
          '


          


          




