name: Tpu-mlir Regression Testing

on:
  push:
  

jobs:
  reuse_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles(find('**/package-lock.json')) }}

          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm init -y
      - run: npm run build --if-present
      - run: tar -zcvf release.tgz package.json

      - name: Pull Docker images
        run: |
          docker pull sophgo/tpuc_dev:latest

  
