name: Tpu-mlir Regression Testing

on: [push]

jobs:
  


  build:
    name: Build my artifact
    runs-on: ubuntu-latest
    steps:
     
 
    
      - name: 设置 Node.js
        uses: actions/setup-node@master
    
      - run: npm init -y
      - run: npm run build --if-present
      
      - name: Pull Docker images
        run: |
            docker pull sophgo/tpuc_dev:latest
      - name: Run Docker Container and YOLOv5 Test
        run: |
          docker run --privileged --name github_actions_test -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '
      
          mkdir model_yolov5s && cd model_yolov5s
          cp ${REGRESSION_PATH}/model/yolov5s.onnx .
          cp -rf ${REGRESSION_PATH}/dataset/COCO2017 .
          cp -rf ${REGRESSION_PATH}/image .
          mkdir workspace && cd workspace
          
          ########### Model to MLIR ###############
        
          # 在此处添加命令并将输出保存到日志文件
       
           ############   yolov5 regression test   ###########
           cd ..
           cd ..
           cd regression 
           ./run.sh 
           '
