name: Check Release Assets

on:
  release:
    types:
      - created

jobs:
  check-assets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Release Assets
        run: |
          release_id=$(jq -r '.release.id' $GITHUB_EVENT_PATH)
          assets_count=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/$release_id/assets" | jq length)
          
          if [[ $assets_count -gt 0 ]]; then
            echo "Release contains assets."
          else
            echo "Release does not contain assets."
          fi
