name: Cache Docker Container Build

on:
  push:

  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
    
   
      - name: Run Docker Container and YOLOv5 Test
        run: |
          docker run --privileged --name myname1234 -v $PWD:/workspace sophgo/tpuc_dev:v2.2 bash -c '
          cd tpu-mlir
          source ./envsetup.sh
          ./build.sh
          '
      
      - name: Save cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}

 
    
         
    
