name: Check Attachments in Releases

on:
  push:
    branches:
      - master

jobs:
  check_attachments:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get Releases
        id: get_releases
        run: |
          releases=$(curl -s "https://api.github.com/repos/OWNER/REPO/releases")
          echo "::set-output name=releases::$releases"
          
      - name: Check Attachments
        run: |
          releases="${{ steps.get_releases.outputs.releases }}"
          no_attachments_found="true"
          
          for release in $(echo "$releases" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${release} | base64 --decode | jq -r ${1}
            }
            
            assets_count=$(_jq '.assets | length')
            
            if [ "$assets_count" -eq 0 ]; then
              echo "Release $(_jq '.name') has no attachments."
              echo "Tag: $(_jq '.tag_name')"
              no_attachments_found="false"
            fi
          done
          
          if [ "$no_attachments_found" = "true" ]; then
            echo "No releases without attachments found."
          fi
