name: Cache Docker Container Build

on:
  push:
         tags：
            - "c*"

  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/tpu-mlir/tpu-mlir/ccache
          key: ${{ runner.os }}-docker-${{ hashFiles('/home/runner/work/tpu-mlir/tpu-mlir/ccache') }}
          restore-keys: |
            ${{ runner.os }}-docker-
    
   
      - name: Run Docker Container and YOLOv5 Test
        run: |
         
          
          docker run --privileged --name myname1234 -v /home/runner/work/tpu-mlir/tpu-mlir/ccache sophgo/tpuc_dev:v2.2   
          docker attach myname1234 -c '
                      #   cp -r $GITHUB_WORKSPACE/tpu-mlir/~/.cache/ccache /root/.cache/ccache
         
          source ./envsetup.sh
          ./build.sh
          '
         
         
      - name: copy
        run: docker cp myname1234:/root/.cache/ccache /home/runner/work/tpu-mlir/tpu-mlir/
      
      - name: Save cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/tpu-mlir/tpu-mlir/ccache
          key: ${{ runner.os }}-docker-${{ hashFiles('/home/runner/work/tpu-mlir/tpu-mlir/ccache') }}

 
    
         
    
