name: Check Release Assets

on:
  push:
     branches:
         - "master"



jobs:
  check-assets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Release Assets
        run: |
          repo_owner="Xieminghe"
          repo_name="tpu-mlir"
          release_id=$(jq -r '.release.id' $GITHUB_EVENT_PATH)
          assets_count=$(curl -s -H "Authorization: Bearer ${{ secrets.RELEASE_TOKEN }}" "https:https://github.com/Xieminghe/tpu-mlir/releases/$release_id/Assets" | jq length)
          release_tag=$(jq -r '.release.tag_name' $GITHUB_EVENT_PATH)
          
          if [[ $assets_count -gt 0 ]]; then
            echo "Release $release_tag in $repo_owner/$repo_name contains assets."
          else
            echo "Release $release_tag in $repo_owner/$repo_name does not contain assets."
          fi


