name: Upload Release Assets


on:
  push:
  
jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Pull Docker image
        run: docker pull sophgo/tpuc_dev:latest

      - name: Run Docker container
        run: |
          docker run --privileged --name myname1234 -v $PWD:/workspace sophgo/tpuc_dev:v2.2 /bin/bash -c "
          ./release.sh
         
          "
     
        

      - name: Read ZIP.GZ File List
        id: read_zip_gz_list
        run: |
          cat zip_gz_files.txt
        continue-on-error: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tpu-mlir/tpu-mlir_v1.3.beta.0-20230817.tar.gz  # 使用查找的文件列表
          asset_name: zip_gz_files.zip  # 上传后的文件名
          asset_content_type: application/zip  # 文件类
