name: Check Releases Without .tar.gz Attachments

on:
  push:
    branches:
      - master

jobs:
  check_releases:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get Releases
        id: get_releases
        run: |
          releases=$(curl -s "https://github.com/Xieminghe/tpu-mlir/releases")
          echo "::set-output name=releases::$releases"
          
      - name: Check Releases
        run: |
          releases="${{ steps.get_releases.outputs.releases }}"
          no_matching_releases="true"
          
          for release in $(echo "$releases" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${release} | base64 --decode | jq -r ${1}
            }
            
            tag_name=$(_jq '.tag_name')
            assets=$(_jq '.assets')
            
            if [ -z "$(echo $assets | jq '.[] | select(.name | endswith(".tar.gz") | not)')" ]; then
              echo "Release $(_jq '.name') has no .tar.gz attachments."
              echo "Tag: $tag_name"
              no_matching_releases="false"
            fi
          done
          
          if [ "$no_matching_releases" = "true" ]; then
            echo "No releases without .tar.gz attachments found."
          fi
