name: Caching Primes

on:
   push:
     branches:
         - "master" #根据项目需求设置触发的分支
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3

    - name: Pull Docker images
      run: |
            docker pull sophgo/tpuc_dev:latest
    - name: Run Docker Container and YOLOv5 Test
      run: |
          docker run --privileged --name github_actions_test -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '

          source ./envsetup.sh
          ./build.sh

           cd regression
           ./run.sh

           '
